#!/bin/bash
#SBATCH --job-name=job_name
#SBATCH --output=/home/maass/shared_folder/job_name_out%j.out
#SBATCH --error=/home/maass/shared_folder/job_name_error%j.err
#SBATCH --time=08:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --gres=gpu:1
#SBATCH --partition=gpu

#SBATCH --partition=acltr

#SBATCH --mail-type=BEGIN,FAIL,END

module load Anaconda3
module load NCCL/2.18.3-GCCcore-12.3.0-CUDA-12.1.1
source activate myenv

# Install required packages
pip install tqdm


# Run the test script
python /home/maass/shared_folder/your_script.py --config_file /home/maass/shared_folder/exmaple_of_a_config_file.json

echo "Task finished."